// Code generated by mockery v2.33.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	sublistdto "moonlay-todolist/internal/dto/sublist"
)

// ISubListService is an autogenerated mock type for the ISubListService type
type ISubListService struct {
	mock.Mock
}

// Create provides a mock function with given fields: payload
func (_m *ISubListService) Create(payload *sublistdto.CreateRequest) (*sublistdto.CreateResponse, error) {
	ret := _m.Called(payload)

	var r0 *sublistdto.CreateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*sublistdto.CreateRequest) (*sublistdto.CreateResponse, error)); ok {
		return rf(payload)
	}
	if rf, ok := ret.Get(0).(func(*sublistdto.CreateRequest) *sublistdto.CreateResponse); ok {
		r0 = rf(payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sublistdto.CreateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*sublistdto.CreateRequest) error); ok {
		r1 = rf(payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteByID provides a mock function with given fields: payload
func (_m *ISubListService) DeleteByID(payload *sublistdto.DeleteByIDRequest) (*sublistdto.DeleteByIDResponse, error) {
	ret := _m.Called(payload)

	var r0 *sublistdto.DeleteByIDResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*sublistdto.DeleteByIDRequest) (*sublistdto.DeleteByIDResponse, error)); ok {
		return rf(payload)
	}
	if rf, ok := ret.Get(0).(func(*sublistdto.DeleteByIDRequest) *sublistdto.DeleteByIDResponse); ok {
		r0 = rf(payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sublistdto.DeleteByIDResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*sublistdto.DeleteByIDRequest) error); ok {
		r1 = rf(payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields: payload
func (_m *ISubListService) FindAll(payload *sublistdto.FindAllRequest) (*sublistdto.FindAllResponse, error) {
	ret := _m.Called(payload)

	var r0 *sublistdto.FindAllResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*sublistdto.FindAllRequest) (*sublistdto.FindAllResponse, error)); ok {
		return rf(payload)
	}
	if rf, ok := ret.Get(0).(func(*sublistdto.FindAllRequest) *sublistdto.FindAllResponse); ok {
		r0 = rf(payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sublistdto.FindAllResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*sublistdto.FindAllRequest) error); ok {
		r1 = rf(payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: payload
func (_m *ISubListService) FindByID(payload *sublistdto.FindByIDRequest) (*sublistdto.FindByIDResponse, error) {
	ret := _m.Called(payload)

	var r0 *sublistdto.FindByIDResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*sublistdto.FindByIDRequest) (*sublistdto.FindByIDResponse, error)); ok {
		return rf(payload)
	}
	if rf, ok := ret.Get(0).(func(*sublistdto.FindByIDRequest) *sublistdto.FindByIDResponse); ok {
		r0 = rf(payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sublistdto.FindByIDResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*sublistdto.FindByIDRequest) error); ok {
		r1 = rf(payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateByID provides a mock function with given fields: payload, files
func (_m *ISubListService) UpdateByID(payload *sublistdto.UpdateByIDRequest, files []string) (*sublistdto.UpdateByIDResponse, error) {
	ret := _m.Called(payload, files)

	var r0 *sublistdto.UpdateByIDResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*sublistdto.UpdateByIDRequest, []string) (*sublistdto.UpdateByIDResponse, error)); ok {
		return rf(payload, files)
	}
	if rf, ok := ret.Get(0).(func(*sublistdto.UpdateByIDRequest, []string) *sublistdto.UpdateByIDResponse); ok {
		r0 = rf(payload, files)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sublistdto.UpdateByIDResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*sublistdto.UpdateByIDRequest, []string) error); ok {
		r1 = rf(payload, files)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewISubListService creates a new instance of ISubListService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewISubListService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ISubListService {
	mock := &ISubListService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
